apiVersion: sparkoperator.k8s.io/v1beta2
kind: SparkApplication
metadata:
  name: python-helloworld-spark-sql
  namespace: test
spec:
  type: Python
  mode: cluster
  image: python-helloworld-spark-sql:0.1
  sparkVersion: "3.0.0"
  mainApplicationFile: local:///tmp/app.py
  mainClass: App
  driver:
    coreRequest: "100m"
    memory: "512m"
    labels:
      version: 3.0.0
    serviceAccount: default
  executor:
    coreRequest: "100m"
    instances: 1
    memory: "512m"
    labels:
      version: 3.0.0
