apiVersion: v1
kind: PersistentVolume
metadata:
  name: connect-plugins-pv
  namespace: kafka
spec:
  capacity:
    storage: 100M
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/connect-plugins"
