kind: Service
apiVersion: v1
metadata:
  name: control-center
  namespace: kafka
spec:
  selector:
    app: control-center
  ports:
  - protocol: TCP
    port: 30921
    nodePort: 30921
    targetPort: 9021
  type: NodePort

