apiVersion: v1
kind: Service
metadata:
  name: connect
  namespace: kafka
spec:
  selector:
    app: connect
  ports:
  - protocol: TCP
    port: 30808
    nodePort: 30808
    targetPort: 30808
  type: NodePort
