apiVersion: v1
kind: Service
metadata:
  name: schema-registry-service-outside
  namespace: kafka
spec:
  selector:
    app: schema-registry
  ports:
  - protocol: TCP
    port: 30801
    nodePort: 30801
    targetPort: 8081
  type: NodePort
